/**
 * Furniture catalog type definitions and data.
 */

export interface FurnitureCatalogItem {
  id: string;
  name: string;
  type: 'bed' | 'desk' | 'chair' | 'wardrobe' | 'table' | 'sofa' | 'shelf' | 'wall-lamp' | 'wall-tv' | 'wall-art' | 'desk-lamp' | 'decoration';
  category: 'bedroom' | 'living' | 'office' | 'kitchen' | 'decoration';
  dimensions: { width: number; height: number; depth: number };
  thumbnail: string;
  color: string;
  price?: number;
  tags: string[];
  mountType?: 'floor' | 'wall' | 'surface'; // floor: 바닥, wall: 벽걸이, surface: 가구 위
}

export const FURNITURE_CATALOG: FurnitureCatalogItem[] = [
  {
    id: 'bed-single',
    name: 'Single Bed',
    type: 'bed',
    category: 'bedroom',
    dimensions: { width: 1.0, height: 0.5, depth: 2.0 },
    thumbnail: '/furniture/bed-single.png',
    color: '#8B4513',
    price: 300,
    tags: ['bed', 'bedroom', 'single'],
  },
  {
    id: 'bed-double',
    name: 'Double Bed',
    type: 'bed',
    category: 'bedroom',
    dimensions: { width: 1.5, height: 0.5, depth: 2.0 },
    thumbnail: '/furniture/bed-double.png',
    color: '#8B4513',
    price: 500,
    tags: ['bed', 'bedroom', 'double'],
  },
  {
    id: 'desk-basic',
    name: 'Basic Desk',
    type: 'desk',
    category: 'office',
    dimensions: { width: 1.2, height: 0.75, depth: 0.6 },
    thumbnail: '/furniture/desk-basic.png',
    color: '#A0522D',
    price: 200,
    tags: ['desk', 'office', 'work'],
  },
  {
    id: 'chair-office',
    name: 'Office Chair',
    type: 'chair',
    category: 'office',
    dimensions: { width: 0.6, height: 1.0, depth: 0.6 },
    thumbnail: '/furniture/chair-office.png',
    color: '#000000',
    price: 150,
    tags: ['chair', 'office', 'seating'],
  },
  {
    id: 'wardrobe-large',
    name: 'Large Wardrobe',
    type: 'wardrobe',
    category: 'bedroom',
    dimensions: { width: 2.0, height: 2.2, depth: 0.6 },
    thumbnail: '/furniture/wardrobe-large.png',
    color: '#DEB887',
    price: 800,
    tags: ['wardrobe', 'storage', 'bedroom'],
  },
  {
    id: 'sofa-3seat',
    name: '3-Seater Sofa',
    type: 'sofa',
    category: 'living',
    dimensions: { width: 2.2, height: 0.85, depth: 0.9 },
    thumbnail: '/furniture/sofa-3seat.png',
    color: '#696969',
    price: 1200,
    tags: ['sofa', 'living', 'seating'],
  },
  {
    id: 'table-dining',
    name: 'Dining Table',
    type: 'table',
    category: 'kitchen',
    dimensions: { width: 1.8, height: 0.75, depth: 0.9 },
    thumbnail: '/furniture/table-dining.png',
    color: '#8B4513',
    price: 600,
    tags: ['table', 'dining', 'kitchen'],
  },
  {
    id: 'shelf-bookcase',
    name: 'Bookcase',
    type: 'shelf',
    category: 'office',
    dimensions: { width: 0.8, height: 2.0, depth: 0.3 },
    thumbnail: '/furniture/shelf-bookcase.png',
    color: '#D2691E',
    price: 400,
    tags: ['shelf', 'storage', 'books'],
  },
  {
    id: 'chair-dining',
    name: 'Dining Chair',
    type: 'chair',
    category: 'kitchen',
    dimensions: { width: 0.5, height: 0.9, depth: 0.5 },
    thumbnail: '/furniture/chair-dining.png',
    color: '#8B4513',
    price: 100,
    tags: ['chair', 'dining', 'seating'],
  },
  {
    id: 'table-coffee',
    name: 'Coffee Table',
    type: 'table',
    category: 'living',
    dimensions: { width: 1.2, height: 0.45, depth: 0.6 },
    thumbnail: '/furniture/table-coffee.png',
    color: '#654321',
    price: 250,
    tags: ['table', 'coffee', 'living'],
  },
  // Wall-mounted items
  {
    id: 'wall-lamp-modern',
    name: 'Modern Wall Lamp',
    type: 'wall-lamp',
    category: 'decoration',
    dimensions: { width: 0.15, height: 0.3, depth: 0.2 },
    thumbnail: '/furniture/wall-lamp.png',
    color: '#FFD700',
    price: 80,
    tags: ['lamp', 'wall', 'lighting'],
    mountType: 'wall',
  },
  {
    id: 'wall-tv-55',
    name: '55" Wall TV',
    type: 'wall-tv',
    category: 'living',
    dimensions: { width: 1.2, height: 0.7, depth: 0.1 },
    thumbnail: '/furniture/wall-tv.png',
    color: '#000000',
    price: 1500,
    tags: ['tv', 'wall', 'entertainment'],
    mountType: 'wall',
  },
  {
    id: 'wall-art-frame',
    name: 'Picture Frame',
    type: 'wall-art',
    category: 'decoration',
    dimensions: { width: 0.6, height: 0.8, depth: 0.05 },
    thumbnail: '/furniture/wall-art.png',
    color: '#8B4513',
    price: 120,
    tags: ['art', 'wall', 'decoration'],
    mountType: 'wall',
  },
  // Surface-mounted items (on furniture)
  {
    id: 'desk-lamp-led',
    name: 'LED Desk Lamp',
    type: 'desk-lamp',
    category: 'office',
    dimensions: { width: 0.2, height: 0.4, depth: 0.2 },
    thumbnail: '/furniture/desk-lamp.png',
    color: '#C0C0C0',
    price: 60,
    tags: ['lamp', 'desk', 'lighting'],
    mountType: 'surface',
  },
  {
    id: 'decoration-vase',
    name: 'Decorative Vase',
    type: 'decoration',
    category: 'decoration',
    dimensions: { width: 0.15, height: 0.3, depth: 0.15 },
    thumbnail: '/furniture/decoration-vase.png',
    color: '#4169E1',
    price: 40,
    tags: ['decoration', 'vase', 'ornament'],
    mountType: 'surface',
  },
  {
    id: 'decoration-plant',
    name: 'Potted Plant',
    type: 'decoration',
    category: 'decoration',
    dimensions: { width: 0.25, height: 0.4, depth: 0.25 },
    thumbnail: '/furniture/decoration-plant.png',
    color: '#228B22',
    price: 50,
    tags: ['decoration', 'plant', 'nature'],
    mountType: 'surface',
  },
];
