/**
 * Furniture catalog type definitions and data.
 */

export interface FurnitureCatalogItem {
  id: string;
  name: string;
  type: 'bed' | 'desk' | 'chair' | 'wardrobe' | 'table' | 'sofa' | 'shelf' | 'wall-lamp' | 'wall-tv' | 'wall-art' | 'desk-lamp' | 'decoration' | 'monitor' | 'printer' | 'filing-cabinet' | 'whiteboard' | 'clock' | 'mirror' | 'shelving-unit';
  category: 'bedroom' | 'living' | 'office' | 'kitchen' | 'decoration';
  dimensions: { width: number; height: number; depth: number };
  thumbnail: string;
  color: string;
  price?: number;
  tags: string[];
  mountType?: 'floor' | 'wall' | 'surface'; // floor: 바닥, wall: 벽걸이, surface: 가구 위
  glbUrl?: string; // S3 GLB file presigned URL
  glbKey?: string; // S3 GLB file key
}

export const FURNITURE_CATALOG: FurnitureCatalogItem[] = [
  {
    id: 'bed-single',
    name: 'Single Bed',
    type: 'bed',
    category: 'bedroom',
    dimensions: { width: 1.0, height: 0.5, depth: 2.0 },
    thumbnail: '/furniture/bed-single.png',
    color: '#8B4513',
    price: 189000,
    tags: ['bed', 'bedroom', 'single'],
  },
  {
    id: 'bed-double',
    name: 'Double Bed',
    type: 'bed',
    category: 'bedroom',
    dimensions: { width: 1.5, height: 0.5, depth: 2.0 },
    thumbnail: '/furniture/bed-double.png',
    color: '#8B4513',
    price: 349000,
    tags: ['bed', 'bedroom', 'double'],
  },
  {
    id: 'desk-basic',
    name: 'Basic Desk',
    type: 'desk',
    category: 'office',
    dimensions: { width: 1.2, height: 0.75, depth: 0.6 },
    thumbnail: '/furniture/desk-basic.png',
    color: '#A0522D',
    price: 89000,
    tags: ['desk', 'office', 'work'],
  },
  {
    id: 'chair-office',
    name: 'Office Chair',
    type: 'chair',
    category: 'office',
    dimensions: { width: 0.6, height: 1.0, depth: 0.6 },
    thumbnail: '/furniture/chair-office.png',
    color: '#000000',
    price: 79000,
    tags: ['chair', 'office', 'seating'],
  },
  {
    id: 'wardrobe-large',
    name: 'Large Wardrobe',
    type: 'wardrobe',
    category: 'bedroom',
    dimensions: { width: 2.0, height: 2.2, depth: 0.6 },
    thumbnail: '/furniture/wardrobe-large.png',
    color: '#DEB887',
    price: 459000,
    tags: ['wardrobe', 'storage', 'bedroom'],
  },
  {
    id: 'sofa-3seat',
    name: '3-Seater Sofa',
    type: 'sofa',
    category: 'living',
    dimensions: { width: 2.2, height: 0.85, depth: 0.9 },
    thumbnail: '/furniture/sofa-3seat.png',
    color: '#696969',
    price: 699000,
    tags: ['sofa', 'living', 'seating'],
  },
  {
    id: 'table-dining',
    name: 'Dining Table',
    type: 'table',
    category: 'kitchen',
    dimensions: { width: 1.8, height: 0.75, depth: 0.9 },
    thumbnail: '/furniture/table-dining.png',
    color: '#8B4513',
    price: 329000,
    tags: ['table', 'dining', 'kitchen'],
  },
  {
    id: 'shelf-bookcase',
    name: 'Bookcase',
    type: 'shelf',
    category: 'office',
    dimensions: { width: 0.8, height: 2.0, depth: 0.3 },
    thumbnail: '/furniture/shelf-bookcase.png',
    color: '#D2691E',
    price: 189000,
    tags: ['shelf', 'storage', 'books'],
  },
  {
    id: 'chair-dining',
    name: 'Dining Chair',
    type: 'chair',
    category: 'kitchen',
    dimensions: { width: 0.5, height: 0.9, depth: 0.5 },
    thumbnail: '/furniture/chair-dining.png',
    color: '#8B4513',
    price: 49000,
    tags: ['chair', 'dining', 'seating'],
  },
  {
    id: 'table-coffee',
    name: 'Coffee Table',
    type: 'table',
    category: 'living',
    dimensions: { width: 1.2, height: 0.45, depth: 0.6 },
    thumbnail: '/furniture/table-coffee.png',
    color: '#654321',
    price: 129000,
    tags: ['table', 'coffee', 'living'],
  },
  // Wall-mounted items
  {
    id: 'wall-lamp-modern',
    name: 'Modern Wall Lamp',
    type: 'wall-lamp',
    category: 'decoration',
    dimensions: { width: 0.15, height: 0.3, depth: 0.2 },
    thumbnail: '/furniture/wall-lamp.png',
    color: '#FFD700',
    price: 39000,
    tags: ['lamp', 'wall', 'lighting'],
    mountType: 'wall',
  },
  {
    id: 'wall-tv-55',
    name: '55" Wall TV',
    type: 'wall-tv',
    category: 'living',
    dimensions: { width: 1.2, height: 0.7, depth: 0.1 },
    thumbnail: '/furniture/wall-tv.png',
    color: '#000000',
    price: 890000,
    tags: ['tv', 'wall', 'entertainment'],
    mountType: 'wall',
  },
  {
    id: 'wall-art-frame',
    name: 'Picture Frame',
    type: 'wall-art',
    category: 'decoration',
    dimensions: { width: 0.6, height: 0.8, depth: 0.05 },
    thumbnail: '/furniture/wall-art.png',
    color: '#8B4513',
    price: 45000,
    tags: ['art', 'wall', 'decoration'],
    mountType: 'wall',
  },
  // Surface-mounted items (on furniture)
  {
    id: 'desk-lamp-led',
    name: 'LED Desk Lamp',
    type: 'desk-lamp',
    category: 'office',
    dimensions: { width: 0.2, height: 0.4, depth: 0.2 },
    thumbnail: '/furniture/desk-lamp.png',
    color: '#C0C0C0',
    price: 29000,
    tags: ['lamp', 'desk', 'lighting'],
    mountType: 'surface',
  },
  {
    id: 'decoration-vase',
    name: 'Decorative Vase',
    type: 'decoration',
    category: 'decoration',
    dimensions: { width: 0.15, height: 0.3, depth: 0.15 },
    thumbnail: '/furniture/decoration-vase.png',
    color: '#4169E1',
    price: 19000,
    tags: ['decoration', 'vase', 'ornament'],
    mountType: 'surface',
  },
  {
    id: 'decoration-plant',
    name: 'Potted Plant',
    type: 'decoration',
    category: 'decoration',
    dimensions: { width: 0.25, height: 0.4, depth: 0.25 },
    thumbnail: '/furniture/decoration-plant.png',
    color: '#228B22',
    price: 25000,
    tags: ['decoration', 'plant', 'nature'],
    mountType: 'surface',
  },
  // Office furniture - Desks
  {
    id: 'desk-l-shaped',
    name: 'L-Shaped Desk',
    type: 'desk',
    category: 'office',
    dimensions: { width: 1.8, height: 0.75, depth: 1.5 },
    thumbnail: '/furniture/desk-l-shaped.png',
    color: '#2F4F4F',
    price: 249000,
    tags: ['desk', 'office', 'l-shaped', 'work'],
  },
  {
    id: 'desk-standing',
    name: 'Standing Desk',
    type: 'desk',
    category: 'office',
    dimensions: { width: 1.4, height: 1.2, depth: 0.7 },
    thumbnail: '/furniture/desk-standing.png',
    color: '#708090',
    price: 349000,
    tags: ['desk', 'office', 'standing', 'ergonomic'],
  },
  {
    id: 'desk-executive',
    name: 'Executive Desk',
    type: 'desk',
    category: 'office',
    dimensions: { width: 2.0, height: 0.75, depth: 1.0 },
    thumbnail: '/furniture/desk-executive.png',
    color: '#8B4513',
    price: 590000,
    tags: ['desk', 'office', 'executive', 'premium'],
  },
  // Office furniture - Chairs
  {
    id: 'chair-ergonomic',
    name: 'Ergonomic Chair',
    type: 'chair',
    category: 'office',
    dimensions: { width: 0.65, height: 1.1, depth: 0.65 },
    thumbnail: '/furniture/chair-ergonomic.png',
    color: '#000080',
    price: 189000,
    tags: ['chair', 'office', 'ergonomic', 'comfort'],
  },
  {
    id: 'chair-guest',
    name: 'Guest Chair',
    type: 'chair',
    category: 'office',
    dimensions: { width: 0.55, height: 0.85, depth: 0.55 },
    thumbnail: '/furniture/chair-guest.png',
    color: '#4682B4',
    price: 59000,
    tags: ['chair', 'office', 'guest', 'seating'],
  },
  // Office furniture - Storage
  {
    id: 'filing-cabinet-2drawer',
    name: '2-Drawer Filing Cabinet',
    type: 'filing-cabinet',
    category: 'office',
    dimensions: { width: 0.5, height: 1.2, depth: 0.6 },
    thumbnail: '/furniture/filing-cabinet.png',
    color: '#696969',
    price: 129000,
    tags: ['storage', 'office', 'filing', 'cabinet'],
  },
  {
    id: 'filing-cabinet-4drawer',
    name: '4-Drawer Filing Cabinet',
    type: 'filing-cabinet',
    category: 'office',
    dimensions: { width: 0.5, height: 1.5, depth: 0.6 },
    thumbnail: '/furniture/filing-cabinet-4drawer.png',
    color: '#696969',
    price: 179000,
    tags: ['storage', 'office', 'filing', 'cabinet'],
  },
  {
    id: 'shelving-unit-office',
    name: 'Office Shelving Unit',
    type: 'shelving-unit',
    category: 'office',
    dimensions: { width: 0.9, height: 1.8, depth: 0.35 },
    thumbnail: '/furniture/shelving-unit.png',
    color: '#D3D3D3',
    price: 139000,
    tags: ['shelf', 'office', 'storage', 'organizer'],
  },
  // Office equipment
  {
    id: 'monitor-27',
    name: '27" Monitor',
    type: 'monitor',
    category: 'office',
    dimensions: { width: 0.6, height: 0.4, depth: 0.25 },
    thumbnail: '/furniture/monitor.png',
    color: '#000000',
    price: 289000,
    tags: ['monitor', 'office', 'display', 'tech'],
    mountType: 'surface',
  },
  {
    id: 'monitor-dual',
    name: 'Dual Monitor Setup',
    type: 'monitor',
    category: 'office',
    dimensions: { width: 1.2, height: 0.4, depth: 0.25 },
    thumbnail: '/furniture/monitor-dual.png',
    color: '#000000',
    price: 549000,
    tags: ['monitor', 'office', 'display', 'dual', 'tech'],
    mountType: 'surface',
  },
  {
    id: 'printer-office',
    name: 'Office Printer',
    type: 'printer',
    category: 'office',
    dimensions: { width: 0.5, height: 0.4, depth: 0.4 },
    thumbnail: '/furniture/printer.png',
    color: '#FFFFFF',
    price: 259000,
    tags: ['printer', 'office', 'equipment', 'tech'],
    mountType: 'surface',
  },
  // Office wall items
  {
    id: 'whiteboard-large',
    name: 'Large Whiteboard',
    type: 'whiteboard',
    category: 'office',
    dimensions: { width: 1.8, height: 1.2, depth: 0.05 },
    thumbnail: '/furniture/whiteboard.png',
    color: '#FFFFFF',
    price: 89000,
    tags: ['whiteboard', 'office', 'wall', 'presentation'],
    mountType: 'wall',
  },
  {
    id: 'whiteboard-small',
    name: 'Small Whiteboard',
    type: 'whiteboard',
    category: 'office',
    dimensions: { width: 1.0, height: 0.7, depth: 0.05 },
    thumbnail: '/furniture/whiteboard-small.png',
    color: '#FFFFFF',
    price: 59000,
    tags: ['whiteboard', 'office', 'wall', 'presentation'],
    mountType: 'wall',
  },
  {
    id: 'clock-wall',
    name: 'Wall Clock',
    type: 'clock',
    category: 'office',
    dimensions: { width: 0.4, height: 0.4, depth: 0.1 },
    thumbnail: '/furniture/clock.png',
    color: '#000000',
    price: 25000,
    tags: ['clock', 'office', 'wall', 'time'],
    mountType: 'wall',
  },
  // Decoration items
  {
    id: 'decoration-sculpture',
    name: 'Decorative Sculpture',
    type: 'decoration',
    category: 'decoration',
    dimensions: { width: 0.2, height: 0.35, depth: 0.2 },
    thumbnail: '/furniture/sculpture.png',
    color: '#C0C0C0',
    price: 79000,
    tags: ['decoration', 'sculpture', 'art', 'ornament'],
    mountType: 'surface',
  },
  {
    id: 'decoration-books',
    name: 'Book Set',
    type: 'decoration',
    category: 'decoration',
    dimensions: { width: 0.3, height: 0.25, depth: 0.2 },
    thumbnail: '/furniture/books.png',
    color: '#8B4513',
    price: 15000,
    tags: ['decoration', 'books', 'office', 'decoration'],
    mountType: 'surface',
  },
  {
    id: 'decoration-pen-holder',
    name: 'Pen Holder',
    type: 'decoration',
    category: 'decoration',
    dimensions: { width: 0.1, height: 0.15, depth: 0.1 },
    thumbnail: '/furniture/pen-holder.png',
    color: '#4169E1',
    price: 8900,
    tags: ['decoration', 'office', 'organizer', 'desk'],
    mountType: 'surface',
  },
  // Wall decoration
  {
    id: 'wall-art-modern',
    name: 'Modern Art Piece',
    type: 'wall-art',
    category: 'decoration',
    dimensions: { width: 0.8, height: 1.0, depth: 0.05 },
    thumbnail: '/furniture/wall-art-modern.png',
    color: '#FF6347',
    price: 89000,
    tags: ['art', 'wall', 'decoration', 'modern'],
    mountType: 'wall',
  },
  {
    id: 'wall-art-large',
    name: 'Large Wall Art',
    type: 'wall-art',
    category: 'decoration',
    dimensions: { width: 1.2, height: 1.5, depth: 0.05 },
    thumbnail: '/furniture/wall-art-large.png',
    color: '#8B4513',
    price: 159000,
    tags: ['art', 'wall', 'decoration', 'large'],
    mountType: 'wall',
  },
  {
    id: 'mirror-wall',
    name: 'Wall Mirror',
    type: 'mirror',
    category: 'decoration',
    dimensions: { width: 0.8, height: 1.2, depth: 0.05 },
    thumbnail: '/furniture/mirror.png',
    color: '#C0C0C0',
    price: 79000,
    tags: ['mirror', 'wall', 'decoration', 'bathroom'],
    mountType: 'wall',
  },
  {
    id: 'wall-lamp-sconce',
    name: 'Wall Sconce',
    type: 'wall-lamp',
    category: 'decoration',
    dimensions: { width: 0.2, height: 0.4, depth: 0.25 },
    thumbnail: '/furniture/wall-sconce.png',
    color: '#FFD700',
    price: 55000,
    tags: ['lamp', 'wall', 'lighting', 'decoration'],
    mountType: 'wall',
  },
  // Additional furniture
  {
    id: 'sofa-2seat',
    name: '2-Seater Sofa',
    type: 'sofa',
    category: 'living',
    dimensions: { width: 1.6, height: 0.85, depth: 0.9 },
    thumbnail: '/furniture/sofa-2seat.png',
    color: '#696969',
    price: 499000,
    tags: ['sofa', 'living', 'seating'],
  },
  {
    id: 'table-side',
    name: 'Side Table',
    type: 'table',
    category: 'living',
    dimensions: { width: 0.5, height: 0.5, depth: 0.5 },
    thumbnail: '/furniture/table-side.png',
    color: '#654321',
    price: 69000,
    tags: ['table', 'side', 'living'],
  },
  {
    id: 'shelf-floating',
    name: 'Floating Shelf',
    type: 'shelf',
    category: 'decoration',
    dimensions: { width: 1.0, height: 0.15, depth: 0.25 },
    thumbnail: '/furniture/shelf-floating.png',
    color: '#8B4513',
    price: 35000,
    tags: ['shelf', 'wall', 'storage', 'decoration'],
    mountType: 'wall',
  },
];
