from fastapi import APIRouter, File, UploadFile, Depends, HTTPException, status
from sqlalchemy.orm import Session
from pathlib import Path
from typing import Dict
import logging

from app.database import get_db
from app.models import Project, User
from app.core.auth import get_current_user
from app.utils.glb_utils import extract_glb_dimensions

logger = logging.getLogger(__name__)

router = APIRouter()


@router.post("/upload-glb/{project_id}")
async def upload_room_glb(
    project_id: int,
    file: UploadFile = File(...),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> Dict:
    """
    Upload GLB file generated by room builder.
    Auto-detects room dimensions from GLB.
    """
    logger.info(f"User {current_user.id} uploading room GLB for project {project_id}")

    # Verify project ownership
    project = db.query(Project).filter(Project.id == project_id).first()
    if not project:
        logger.error(f"Project {project_id} not found")
        raise HTTPException(status_code=404, detail="Project not found")

    if project.owner_id != current_user.id:
        logger.error(f"User {current_user.id} not authorized for project {project_id}")
        raise HTTPException(status_code=403, detail="Not authorized to modify this project")

    # Validate file type
    if not file.filename.lower().endswith('.glb'):
        raise HTTPException(
            status_code=400,
            detail="Invalid file type. Only GLB files are accepted."
        )

    try:
        # Read file content
        file_content = await file.read()
        file_size = len(file_content)

        # Create GLB directory if it doesn't exist
        glb_dir = Path("uploads/glb_files")
        glb_dir.mkdir(parents=True, exist_ok=True)

        # Generate unique filename
        filename = f"room_{project_id}_{current_user.id}.glb"
        file_path = glb_dir / filename

        # Save file
        with open(file_path, "wb") as f:
            f.write(file_content)

        logger.info(f"Saved GLB file to {file_path} ({file_size} bytes)")

        # Extract dimensions from GLB
        try:
            dimensions = extract_glb_dimensions(file_path)
            logger.info(f"Extracted dimensions from GLB: {dimensions}")
        except Exception as e:
            logger.warning(f"Failed to extract dimensions from GLB: {e}")
            # Use default dimensions if extraction fails
            dimensions = {
                'width': 5.0,
                'height': 3.0,
                'depth': 4.0
            }

        # Update project with GLB info
        project.has_3d_file = True
        project.file_type = 'glb'
        project.file_path = str(file_path)
        project.file_size = file_size
        project.room_width = dimensions['width']
        project.room_height = dimensions['height']
        project.room_depth = dimensions['depth']

        # Also update legacy fields for compatibility
        project.has_ply_file = False
        project.ply_file_path = None
        project.ply_file_size = None

        db.commit()
        db.refresh(project)

        logger.info(f"Successfully uploaded room GLB for project {project_id}")

        return {
            "message": "Room GLB uploaded successfully",
            "project_id": project_id,
            "dimensions": dimensions,
            "file_size": file_size,
            "file_path": str(file_path),
        }

    except Exception as e:
        logger.error(f"Error uploading room GLB: {e}")
        db.rollback()
        raise HTTPException(
            status_code=500,
            detail=f"Failed to upload room GLB: {str(e)}"
        )


@router.get("/dimensions/{project_id}")
async def get_room_dimensions(
    project_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> Dict:
    """
    Get room dimensions for a project.
    """
    project = db.query(Project).filter(Project.id == project_id).first()
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")

    if project.owner_id != current_user.id:
        raise HTTPException(status_code=403, detail="Not authorized to view this project")

    return {
        "project_id": project_id,
        "dimensions": {
            "width": project.room_width,
            "height": project.room_height,
            "depth": project.room_depth,
        },
        "has_3d_file": project.has_3d_file,
        "file_type": project.file_type,
    }