"""Initial migration

Revision ID: 978ad20bee30
Revises: fcc45089e83b
Create Date: 2025-11-21 09:12:50.610092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978ad20bee30'
down_revision = 'fcc45089e83b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
