"""Add GLB file support

Revision ID: 3f8308d86dc1
Revises: 978ad20bee30
Create Date: 2025-11-21 18:44:51.335129

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3f8308d86dc1"
down_revision = "978ad20bee30"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with default values for SQLite compatibility
    op.add_column("projects", sa.Column("has_3d_file", sa.Boolean(), nullable=False, server_default="0"))
    op.add_column("projects", sa.Column("file_type", sa.String(), nullable=True))
    op.add_column("projects", sa.Column("file_path", sa.String(), nullable=True))
    op.add_column("projects", sa.Column("file_size", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "file_size")
    op.drop_column("projects", "file_path")
    op.drop_column("projects", "file_type")
    op.drop_column("projects", "has_3d_file")
    # ### end Alembic commands ###
