"""Initial migration

Revision ID: fcc45089e83b
Revises: 014ea31b324f
Create Date: 2025-11-21 08:40:21.303571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc45089e83b'
down_revision = '014ea31b324f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
