"""add_free_build_support

Revision ID: 186be348bec8
Revises: 3f8308d86dc1
Create Date: 2025-11-30 23:43:37.099104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186be348bec8'
down_revision = '3f8308d86dc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # JSONEncodedDict is stored as TEXT in the database
    op.add_column('layouts', sa.Column('tile_state', sa.TEXT(), nullable=True))
    op.add_column('projects', sa.Column('room_structure', sa.TEXT(), nullable=True))
    op.add_column('projects', sa.Column('build_mode', sa.String(), nullable=True, server_default='template'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'build_mode')
    op.drop_column('projects', 'room_structure')
    op.drop_column('layouts', 'tile_state')
    # ### end Alembic commands ###
